### ISSUE TITLE
Frank Energie API is changed; Personalised queries are broken

### ISSUE THREAD

**Issue by DCSBL** [DCSBL/python-frank-energie#136]
See https://github.com/bajansen/home-assistant-frank_energie/issues/101

**Comment by berendhaan** [comment]
I'm not seeing any issues with the HA integration atm, are you still aware of some issues regarding the 'personalized' queries?

**Comment by DCSBL** [comment]
Oh, I am not using the integration anymore.. so I have no idea to be honest.

But that issue in HA was fixed, maybe I forgot to close this one. Does everything work on your side? Then I will close this one!

**Comment by berendhaan** [comment]
All data seems correct, it also works with a second site, I just recently re-subscribed to Frank.

**Comment by DCSBL** [comment]
Okay! Thank you for the heads-up!

**Comment by HiDiHo01** [comment]
It happend again
